name: "Terraform CI/CD"

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - "terraform-project/**" # Only run when terraform files change
      - "terraform_automate.py"
  workflow_dispatch: # Allows manual triggering

jobs:
  terraform:
    name: "Terraform Scan & Execution"
    runs-on: ubuntu-latest
    permissions:
      contents: write # Grant permission to write to the repository

    # strategy:
    #   matrix:
    #     python-version: ["3.10", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          # This installs the latest 3.13.x (≥ 3.13.0)
        # with:
        #   python-version: ${{ matrix.python-version }}
      - name: Print Python Version
        run: |
          python --version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change to your desired AWS region
      - name: Install and Run Checkov
        run: |
          pip install checkov
          # Scan the terraform-project directory.
          # --soft-fail will ensure the workflow continues even if issues are found,
          # allowing you to review them without blocking deployment.
          checkov --directory terraform-project --soft-fail --output cli > checkov_results.txt
      - name: Commit Checkov Results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update Checkov scan results"
          file_pattern: checkov_results.txt
      - name: Run Terraform Automation Script
        run: python terraform_automate.py
